Home work2 page object web elements
lTsMaineCoon/TestFramePriceNavigator pull request #2
Opened 2020-09-09 13:29 UTC by lTsMaineCoon

2020-09-09 13:50 UTC, DmitriyBondarenko commented on src/main/java/pages/CataloguePage.java
>      private Random r;
Please, rename this variable to smth more understandable or even remove it. Because looks like it's never used.

2020-09-09 13:50 UTC, DmitriyBondarenko commented on src/main/java/pages/CataloguePage.java
> +
Remove LB please

2020-09-09 13:52 UTC, DmitriyBondarenko commented on src/main/java/pages/ComparingPage.java
>      public static String getComparingLink() throws InterruptedException {
Code format please

2020-09-09 13:57 UTC, DmitriyBondarenko commented on src/main/java/pages/HeaderAnyPage.java
>      public HeaderAnyPage enterSearchQueryIntoSearchFieldAndPressEnter(String searchQuery) throws InterruptedException {
Just `enterSearchQuery`

2020-09-09 13:57 UTC, DmitriyBondarenko commented on src/main/java/pages/HeaderAnyPage.java
> +        searchField.sendKeys(searchQuery);
`searchField.sendKeys(searchQuery, Keys.ENTER);`

2020-09-09 13:58 UTC, DmitriyBondarenko commented on src/main/java/pages/HeaderAnyPage.java
> +    public HeaderAnyPage enterSearchQueryIntoSearchFieldAndClearTheSearchField(String searchQuery) throws InterruptedException {
Just `enterSearchQueryAndClear`

2020-09-09 13:59 UTC, DmitriyBondarenko commented on src/main/java/pages/MainPage.java
> +    WebElement emailLoginField;
Please, make a one line break between all WebElements

2020-09-09 14:02 UTC, DmitriyBondarenko commented on src/test/java/TestRunner.java
> +    public void checkThatSiteDefautlCityIsKh() throws InterruptedException {
Fix typo please

2020-09-09 14:03 UTC, DmitriyBondarenko commented on src/test/java/TestRunner.java
> +        HeaderAnyPage page = new HeaderAnyPage(super.driver);
Just `new HeaderAnyPage(super.driver);`

2020-09-09 14:06 UTC, DmitriyBondarenko commented on src/test/java/TestRunner.java
>      public void testFavoriteShopsFeature() throws InterruptedException {
Please, do not push to remote repository not implemented/ready code. And not useful comments.

2020-09-09 14:14 UTC, DmitriyBondarenko requested changes
Fix comments

2020-09-09 16:26 UTC, lTsMaineCoon commented on src/main/java/pages/HeaderAnyPage.java
> +    public HeaderAnyPage enterSearchQueryIntoSearchFieldAndClearTheSearchField(String searchQuery) throws InterruptedException {
deleted unused method

2020-09-09 16:34 UTC, lTsMaineCoon commented on src/test/java/TestRunner.java
> +    public void checkThatSiteDefautlCityIsKh() throws InterruptedException {
fixed

2020-09-10 14:50 UTC, DmitriyBondarenko approved these changes

2020-09-10 14:54 UTC, merged